
project_id = "crwbnkeadskmggpvkgin"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
inmemory = false

[[storage.buckets]]
name = "posts"
public = true

[functions.map-assistant]
verify_jwt = false
